version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    command: sleep infinity
    volumes:
      - ../:/workspace
  backend:
    build:
      context: ../../multi-repo-dev-container-backend/.devcontainer
      dockerfile: Dockerfile
    working_dir: /workspace
    # command: sleep infinity
    volumes:
      - ../../multi-repo-dev-container-backend:/workspace
  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
